name: Package

on:
    workflow_dispatch:

jobs:
    linux:
        runs-on: ubuntu-latest
        name: Linux AppImage Build
        container: debian:bullseye
        steps:
            - name: Install dependencies
              run: |
                  apt update -y
                  apt install -y g++ libmpg123-dev libmp3lame-dev libsndfile1-dev libsoundtouch-dev libminizip-dev zlib1g-dev \
                  libfltk1.3-dev meson wget tar zstd gzip file fuse libfuse2

            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure
              run: meson setup --prefix=/usr builddir --optimization=s -Ddebug=false -Dstrip=true

            - name: Build
              run: ninja -v -C builddir

            - name: Download linuxdeploy
              run: wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage

            - name: Make AppDir
              run: |
                  DESTDIR=$PWD/AppDir meson install -C builddir
                  rm AppDir/usr/bin/cosu-cleanup AppDir/usr/bin/osumem

            - name: Create AppImage
              run: |
                  chmod +x linuxdeploy-x86_64.AppImage
                  ./linuxdeploy-x86_64.AppImage --appimage-extract
                  ./squashfs-root/usr/bin/linuxdeploy --appdir=AppDir -d AppDir/usr/share/applications/cosu-trainer.desktop -i AppDir/usr/share/pixmaps/cosutrainer.png -o appimage

            - name: Pack tarball
              run: |
                  ls -al
                  mkdir package
                  cp builddir/osumem builddir/cosu-cleanup cosu-trainer-*.AppImage COPYING.md package
                  tar cf - -C package . | zstd -9 > cosu-trainer-bin.tar.zst

            - name: Upload a package
              uses: actions/upload-artifact@v4
              with:
                  name: cosu-trainer-bin
                  path: cosu-trainer-bin.tar.zst

    win:
        runs-on: windows-latest
        name: Windows Build
        steps:
            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v2

            - name: Checkout
              uses: actions/checkout@v4

            - name: Update and integrate vcpkg
              id: vcpkg-update
              shell: pwsh
              run: |
                cd C:\vcpkg; git pull
                .\bootstrap-vcpkg.bat; .\vcpkg.exe integrate install
                echo vcpkg $(git log -1 --format=%H).Trim()
                echo "sha=$(git log -1 --format=%H).Trim()" >> "$GITHUB_OUTPUT"

            - name: Restore vcpkg
              uses: actions/cache/restore@v4
              with:
                  path: C:\vcpkg
                  key: vcpkg-${{ steps.vcpkg-update.outputs.sha }}

            - name: Build
              env:
                  VCPKG_ROOT: C:\vcpkg
              run: cd vcpp && msbuild .\cosu-trainer.sln /p:Configuration="Release" /p:Platform="x64"

            - name: Package
              run: |
                  mkdir package
                  Copy-Item -Path vcpp\x64\Release\*.exe -Destination package
                  Copy-Item -Path vcpp\x64\Release\*.dll -Destination package
                  Copy-Item -Path COPYING.md -Destination package
                  Copy-Item -Path docs\cosutrainer.png -Destination package

            - name: Upload a package
              uses: actions/upload-artifact@v4
              with:
                  name: cosu-trainer-win-bin
                  path: package/*
                  compression-level: 9

            - name: Cache vcpkg
              uses: actions/cache/save@v4
              with:
                  path: C:\vcpkg
                  key: vcpkg-${{ steps.vcpkg-update.outputs.sha }}
